[tool.poetry]
name = "aerich"
version = "0.2.1"
description = "A database migrations tool for Tortoise ORM."
authors = ["long2ice <long2ice@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/long2ice/aerich"
repository = "https://github.com/long2ice/aerich.git"
documentation = "https://github.com/long2ice/aerich"
keywords = ["migrate", "Tortoise-ORM", "mysql"]
packages = [
    { include = "aerich" }
]
include = ["CHANGELOG.rst", "LICENSE", "README.md"]

[tool.poetry.dependencies]
python = "^3.8"
tortoise-orm = "*"
asyncclick = "*"
pydantic = "*"
aiomysql = {version = "*", optional = true}
asyncpg = {version = "*", optional = true}

[tool.poetry.dev-dependencies]
flake8 = "*"
isort = "*"
black = "^19.10b0"
pytest = "*"
pytest-xdist = "*"
pytest-asyncio = "*"
bandit = "*"

[tool.poetry.extras]
dbdrivers = ["aiomysql", "asyncpg"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
aerich = "aerich.cli:main"